/** Generates catalog documentation FROM the canonical machine report. */
import { readFileSync, writeFileSync } from 'node:fs';
const r = JSON.parse(readFileSync('data/usda-import-report.json', 'utf8'));
const s = r.stats, q = r.search;
const cov = r.coverage.map((c: any) => `| ${c.nutrientId} | ${c.known}/${c.total} | ${c.percent}% |`).join('\n');
const L: string[] = [];
const p = (x: string) => L.push(x);

p('# 27 — Generic Catalog Semantic Integrity and Search');
p('');
p('> **GENERIC CATALOG SEMANTIC INTEGRITY — CLOSED.**');
p('> **REAL GENERIC CATALOG DEPTH — ESTABLISHED (bounded by supplied archives).**');
p('> **REAL GENERIC SEARCH QUALITY BASELINE — ESTABLISHED.**');
p('>');
p('> Every metric below is read from `data/usda-import-report.json`, the single');
p('> machine-generated source of truth. Nothing is hand-copied.');
p('');
p('## 1. Archives actually available');
p('');
p(`Ingested: ${r.archives.map((a: any) => `${a.dataset} (\`${a.sha256.slice(0, 16)}…\`)`).join(', ')}`);
p('');
p(`**Missing this session: ${r.missingArchives.length > 0 ? r.missingArchives.join(', ') : 'none'}**`);
p('');
// CONDITIONAL. Prose about archive availability is derived from the report,
// never written unconditionally — a fixed sentence claiming SR was missing
// survived alongside a table showing it present, and the document contradicted
// itself.
if (r.missingArchives.length > 0) {
  p(`Depth is bounded: ${r.missingArchives.join(', ')} ${r.missingArchives.length === 1 ? 'was' : 'were'} not`);
  p('available for this run. Reported rather than compensated for with');
  p('remembered data.');
} else {
  p('All expected archives were present for this run, so catalog depth reflects');
  p('the full supplied source population.');
}
p('');
p('## 2. The preparation bug');
p('');
p('USDA writes `Apples, raw, without skin, cooked, boiled`. The old classifier');
p('tested `raw` **before** cooked terms, so a leading word describing the INPUT');
p('overrode the trailing FINAL state — two records published as `raw` carrying');
p('cooked nutrition.');
p('');
p(`\`${r.classifierVersion}\` now resolves by **final state**: when both appear the`);
p('LAST preparation term wins. Genuine alternatives ("raw or cooked") stay');
p('`unresolved` and route to curation rather than being guessed.');
p('');
p('## 3. Taxonomy');
p('');
p('The contract already had four states; no parallel field was invented.');
p('');
p('| State | Meaning |');
p('|---|---|');
p('| raw | weighed uncooked |');
p('| cooked | weighed after cooking |');
p('| as_sold | weighed exactly as purchased — cheese, yogurt, hummus, dried egg, fresh produce |');
p('| unresolved | never published |');
p('');
p('**Cheese is not raw milk; bread is not cooked flour.** Forcing ready-to-eat');
p('foods into raw/cooked merely to permit publication would state something false');
p('about what is on the scale.');
p('');
p(`Published distribution: \`${JSON.stringify(s.publishedPreparationCounts)}\``);
p('');
p(`Source-scan distribution (larger population): \`${JSON.stringify(s.sourcePreparationCounts)}\``);
p('');
p('These are **different populations**. An unscoped `preparationCounts` left the');
p('denominator ambiguous and was mis-cited in a prior closure report; both are now');
p('named explicitly and asserted against the catalog file.');
p('');
p('## 4. Identity');
p('');
p('| Concept | Form |');
p('|---|---|');
p('| MACROS.AI food identity | `food_<16 hex>`, content-addressed from the food concept |');
p('| ProductVersion identity | unchanged |');
p('| External source identity | `{provider, dataset, sourceRecordId, release, archiveSha256}` |');
p('');
p('`usda-fdc-173928` was a source id wearing our namespace — USDA numbering was');
p('effectively our identity, and a second source could never attach to the same');
p('food. Preparation is part of the concept key, so raw and cooked chicken breast');
p('can never share an id.');
p('');
p('## 5. Overlap and source priority');
p('');
p('Deterministic evidence only — normalized description, preparation, category.');
p('Verdicts: `definite_same` / `possible_duplicate` / `distinct`. **No embeddings,');
p('no LLM, no fuzzy merge**: a wrong merge silently attaches the wrong nutrition');
p('to a logged food. Foundation outranks SR Legacy where concepts genuinely match;');
p('values are never averaged.');
p('');
p(`## 6. Category policy (\`${r.catalogPolicyVersion}\`)`);
p('');
p('Three separate questions: what we ingest, what enters the consumer catalog,');
p('and what may be recommended. Baby Foods and Infant Formula remain ingestable');
p('but are **excluded from the adult catalog** — their macros can fit a gap');
p('perfectly and still be an absurd suggestion. Spices, oils and alcohol are');
p('searchable but not recommended.');
p('');
p(`Recommendable: **${s.recommendableCount} of ${s.publishedSeed}**.`);
p('');
p('## 7. Import results');
p('');
p('| | |');
p('|---|---|');
p(`| Records read | ${s.recordsRead} |`);
p(`| Null / malformed | ${s.nullRecords} / ${s.malformed} |`);
p(`| Rejected — unresolved preparation | ${s.rejectedUnresolvedPreparation} |`);
p(`| Rejected — missing core nutrients | ${s.rejectedMissingCore} |`);
p(`| Rejected — excluded category | ${s.rejectedExcludedCategory} |`);
p(`| Duplicate concepts collapsed | ${s.duplicateConceptsCollapsed} |`);
p(`| **Published catalog** | **${s.publishedSeed}** |`);
p('');
p(`Source mapping rows: **${r.sourceMappingRows}**. Canonical nutrients mapped:`);
p(`**${r.canonicalNutrientsMapped}**. These are different metrics — the ambiguous`);
p('`mappedNutrients` is gone, which is what allowed the count to drift.');
p('');
p(`## 8. Search (\`${r.aliasPolicyVersion}\`)`);
p('');
p('| Metric | Result |');
p('|---|---|');
p(`| Corpus | ${q.corpusSize} |`);
p(`| Queries (scored) | ${q.totalQueries} (${q.scoredQueries}) |`);
p(`| Top-1 | **${q.top1Percent}%** |`);
p(`| Top-4 | **${q.top4Percent}%** |`);
p(`| MRR | **${q.mrr}** |`);
p(`| Unambiguous Top-1 | ${q.unambiguous.top1}/${q.unambiguous.total} (${q.unambiguous.percent}%) |`);
p(`| Ambiguous Top-4 | ${q.ambiguous.top4}/${q.ambiguous.total} (${q.ambiguous.percent}%) |`);
p(`| Zero-result correctness | ${q.zeroResult.correct}/${q.zeroResult.total} |`);
p(`| False positives | **${q.falsePositives}** |`);
p(`| Misses | ${q.misses.length > 0 ? q.misses.join(', ') : 'none'} |`);
p('');
p('### Preparation-sensitive search');
p('');
p('Wrong preparation is a **high-severity** error — cooked beef is roughly a');
p('third denser in energy than raw, so a mix-up silently corrupts a log.');
p('');
p('| Metric | Result |');
p('|---|---|');
p(`| Preparation-sensitive queries | ${q.preparationSensitive.total} |`);
p(`| Correct preparation Top-1 | ${q.preparationSensitive.top1}/${q.preparationSensitive.total} (${q.preparationSensitive.top1Percent}%) |`);
p(`| Correct preparation Top-4 | ${q.preparationSensitive.top4}/${q.preparationSensitive.total} (${q.preparationSensitive.top4Percent}%) |`);
p(`| **Wrong preparation outranking correct** | **${q.preparationSensitive.wrongPreparationOutranked}** |`);
p('');
p('This metric previously read `0/0` — preparation correctness was declared but');
p('never actually measured.');
p('');
p('Ambiguous queries are scored on **Top-4, not Top-1**: "rice" legitimately');
p('returns several foods and the A/B/C/D confirmation resolves it. A wrong food is');
p('worse than asking, so ambiguity is preserved rather than optimized away, and no');
p('search result auto-logs. No embeddings and no typo correction were added — the');
p('benchmark shows no failure class lexical matching cannot handle.');
p('');
p(`Common-food coverage: **${q.conceptMatrix.available}/${q.conceptMatrix.total}** concepts available.`);
p('');
p('## 9. Nutrient coverage (published catalog)');
p('');
p('| Nutrient | Known / total | % |');
p('|---|---|---|');
p(cov);
p('');
p('**Added sugars remains 0%** — genuinely absent from Foundation. A description');
p('saying "with added sugar" never produces a numeric added-sugar amount.');
p('');
p('## 10. Known limitations');
p('');
if (r.missingArchives.length > 0) {
  p(`- Depth is bounded — missing: ${r.missingArchives.join(', ')}.`);
} else {
  p(`- Depth reflects all supplied archives (${r.archives.map((a: any) => a.dataset).join(' + ')}).`);
}
p(`- ${q.misses.length} search misses are catalog gaps, not ranking failures.`);
p('- Overlap assessment is implemented and tested but had no cross-source pairs.');
p('- Search metrics come from a human-authored regression corpus, not real users.');

writeFileSync('/mnt/user-data/outputs/macros-architecture/27-generic-catalog-semantic-integrity-and-search.md', L.join('\n') + '\n');
console.log('generated from report | published', s.publishedSeed, '| Top-1', q.top1Percent + '%');
