/**
 * SEARCH-1 GOLDEN CORPUS — 255 queries.
 *
 * Ported from Python to TypeScript so the corpus and the algorithm it measures
 * live in one language and one place. Contents are UNCHANGED: no query was
 * added, removed or re-expected during SEARCH-1B.
 *
 * `requiredAny` — a relevant result must contain every token listed. Expressed
 * as tokens rather than a product id because the catalog legitimately carries
 * many correct answers to "banana", and pinning one would make the benchmark
 * brittle rather than meaningful.
 *
 * `forbidden` is the safety half. For `chiken breast`, turkey is forbidden: a
 * result containing it is not merely irrelevant, it is an UNSAFE WRONG ANSWER.
 */
export interface GoldenQuery {
  readonly query: string;
  readonly category: string;
  readonly requiredAny: readonly string[];
  readonly forbidden: readonly string[];
  /** `resolve` — a confident answer is correct.
   *  `ambiguous` — several distinct foods are genuinely valid.
   *  `absent` — nothing in the catalog should answer this. */
  readonly expectation: 'resolve' | 'ambiguous' | 'absent';
}

export const CORPUS: readonly GoldenQuery[] = [
  { query: 'chicken breast', category: 'protein', requiredAny: ['chicken'], forbidden: ['turkey', 'pork', 'beef'], expectation: 'ambiguous' },
  { query: 'cooked chicken breast', category: 'protein', requiredAny: ['chicken'], forbidden: ['turkey', 'pork'], expectation: 'resolve' },
  { query: 'raw chicken breast', category: 'protein', requiredAny: ['chicken'], forbidden: ['turkey', 'pork'], expectation: 'resolve' },
  { query: 'grilled chicken', category: 'protein', requiredAny: ['chicken'], forbidden: ['turkey'], expectation: 'resolve' },
  { query: 'chicken thigh', category: 'protein', requiredAny: ['chicken'], forbidden: ['turkey'], expectation: 'resolve' },
  { query: 'ground beef', category: 'protein', requiredAny: ['beef'], forbidden: ['chicken', 'turkey', 'pork'], expectation: 'resolve' },
  { query: 'lean ground beef', category: 'protein', requiredAny: ['beef'], forbidden: ['chicken', 'turkey'], expectation: 'resolve' },
  { query: 'steak', category: 'protein', requiredAny: ['steak', 'beef'], forbidden: ['chicken'], expectation: 'ambiguous' },
  { query: 'pork chop', category: 'protein', requiredAny: ['pork'], forbidden: ['chicken', 'beef'], expectation: 'resolve' },
  { query: 'bacon', category: 'protein', requiredAny: ['bacon'], forbidden: [], expectation: 'resolve' },
  { query: 'turkey breast', category: 'protein', requiredAny: ['turkey'], forbidden: ['chicken'], expectation: 'resolve' },
  { query: 'ground turkey', category: 'protein', requiredAny: ['turkey'], forbidden: ['chicken', 'beef'], expectation: 'resolve' },
  { query: 'salmon', category: 'protein', requiredAny: ['salmon'], forbidden: ['tuna'], expectation: 'resolve' },
  { query: 'grilled salmon', category: 'protein', requiredAny: ['salmon'], forbidden: ['tuna'], expectation: 'resolve' },
  { query: 'canned tuna', category: 'protein', requiredAny: ['tuna'], forbidden: ['salmon'], expectation: 'resolve' },
  { query: 'tuna', category: 'protein', requiredAny: ['tuna'], forbidden: ['salmon'], expectation: 'resolve' },
  { query: 'shrimp', category: 'protein', requiredAny: ['shrimp'], forbidden: [], expectation: 'resolve' },
  { query: 'cod', category: 'protein', requiredAny: ['cod'], forbidden: [], expectation: 'resolve' },
  { query: 'tilapia', category: 'protein', requiredAny: ['tilapia'], forbidden: [], expectation: 'resolve' },
  { query: 'lamb', category: 'protein', requiredAny: ['lamb'], forbidden: ['beef', 'pork'], expectation: 'resolve' },
  { query: 'ham', category: 'protein', requiredAny: ['ham'], forbidden: ['turkey'], expectation: 'resolve' },
  { query: 'sausage', category: 'protein', requiredAny: ['sausage'], forbidden: [], expectation: 'resolve' },
  { query: 'eggs', category: 'protein', requiredAny: ['egg'], forbidden: [], expectation: 'resolve' },
  { query: 'egg', category: 'protein', requiredAny: ['egg'], forbidden: [], expectation: 'resolve' },
  { query: 'boiled egg', category: 'protein', requiredAny: ['egg'], forbidden: [], expectation: 'resolve' },
  { query: 'scrambled eggs', category: 'protein', requiredAny: ['egg'], forbidden: [], expectation: 'resolve' },
  { query: 'egg white', category: 'protein', requiredAny: ['egg'], forbidden: [], expectation: 'resolve' },
  { query: 'tofu', category: 'protein', requiredAny: ['tofu'], forbidden: ['tempeh'], expectation: 'resolve' },
  { query: 'firm tofu', category: 'protein', requiredAny: ['tofu'], forbidden: [], expectation: 'resolve' },
  { query: 'tempeh', category: 'protein', requiredAny: ['tempeh'], forbidden: ['tofu'], expectation: 'resolve' },
  { query: 'whey protein', category: 'protein', requiredAny: ['whey', 'protein'], forbidden: [], expectation: 'resolve' },
  { query: 'protein powder', category: 'protein', requiredAny: ['protein'], forbidden: [], expectation: 'resolve' },
  { query: 'white rice', category: 'grain', requiredAny: ['rice'], forbidden: [], expectation: 'resolve' },
  { query: 'brown rice', category: 'grain', requiredAny: ['rice'], forbidden: [], expectation: 'resolve' },
  { query: 'white rice cooked', category: 'grain', requiredAny: ['rice'], forbidden: [], expectation: 'resolve' },
  { query: 'basmati rice', category: 'grain', requiredAny: ['rice'], forbidden: [], expectation: 'resolve' },
  { query: 'jasmine rice', category: 'grain', requiredAny: ['rice'], forbidden: [], expectation: 'resolve' },
  { query: 'pasta', category: 'grain', requiredAny: ['pasta', 'macaroni', 'spaghetti'], forbidden: [], expectation: 'ambiguous' },
  { query: 'spaghetti', category: 'grain', requiredAny: ['spaghetti', 'pasta'], forbidden: [], expectation: 'resolve' },
  { query: 'penne', category: 'grain', requiredAny: ['penne', 'pasta'], forbidden: [], expectation: 'resolve' },
  { query: 'bread', category: 'grain', requiredAny: ['bread'], forbidden: [], expectation: 'ambiguous' },
  { query: 'white bread', category: 'grain', requiredAny: ['bread'], forbidden: [], expectation: 'resolve' },
  { query: 'whole wheat bread', category: 'grain', requiredAny: ['bread', 'wheat'], forbidden: [], expectation: 'resolve' },
  { query: 'sourdough', category: 'grain', requiredAny: ['sourdough'], forbidden: [], expectation: 'resolve' },
  { query: 'bagel', category: 'grain', requiredAny: ['bagel'], forbidden: [], expectation: 'resolve' },
  { query: 'tortilla', category: 'grain', requiredAny: ['tortilla'], forbidden: [], expectation: 'resolve' },
  { query: 'oats', category: 'grain', requiredAny: ['oat'], forbidden: [], expectation: 'resolve' },
  { query: 'rolled oats', category: 'grain', requiredAny: ['oat'], forbidden: [], expectation: 'resolve' },
  { query: 'oatmeal', category: 'grain', requiredAny: ['oat'], forbidden: [], expectation: 'resolve' },
  { query: 'quinoa', category: 'grain', requiredAny: ['quinoa'], forbidden: [], expectation: 'resolve' },
  { query: 'couscous', category: 'grain', requiredAny: ['couscous'], forbidden: [], expectation: 'resolve' },
  { query: 'barley', category: 'grain', requiredAny: ['barley'], forbidden: [], expectation: 'resolve' },
  { query: 'cereal', category: 'grain', requiredAny: ['cereal'], forbidden: [], expectation: 'ambiguous' },
  { query: 'potato', category: 'grain', requiredAny: ['potato'], forbidden: ['sweet'], expectation: 'ambiguous' },
  { query: 'baked potato', category: 'grain', requiredAny: ['potato'], forbidden: [], expectation: 'resolve' },
  { query: 'sweet potato', category: 'grain', requiredAny: ['potato'], forbidden: [], expectation: 'resolve' },
  { query: 'mashed potatoes', category: 'grain', requiredAny: ['potato'], forbidden: [], expectation: 'resolve' },
  { query: 'french fries', category: 'grain', requiredAny: ['fries', 'potato'], forbidden: [], expectation: 'resolve' },
  { query: 'corn', category: 'grain', requiredAny: ['corn'], forbidden: [], expectation: 'ambiguous' },
  { query: 'noodles', category: 'grain', requiredAny: ['noodle'], forbidden: [], expectation: 'ambiguous' },
  { query: 'whole milk', category: 'dairy', requiredAny: ['milk'], forbidden: [], expectation: 'resolve' },
  { query: 'skim milk', category: 'dairy', requiredAny: ['milk'], forbidden: [], expectation: 'resolve' },
  { query: 'milk', category: 'dairy', requiredAny: ['milk'], forbidden: [], expectation: 'ambiguous' },
  { query: 'almond milk', category: 'dairy', requiredAny: ['almond', 'milk'], forbidden: [], expectation: 'resolve' },
  { query: 'oat milk', category: 'dairy', requiredAny: ['oat', 'milk'], forbidden: [], expectation: 'resolve' },
  { query: 'greek yogurt', category: 'dairy', requiredAny: ['yogurt'], forbidden: [], expectation: 'resolve' },
  { query: 'yogurt', category: 'dairy', requiredAny: ['yogurt'], forbidden: [], expectation: 'ambiguous' },
  { query: 'plain yogurt', category: 'dairy', requiredAny: ['yogurt'], forbidden: [], expectation: 'resolve' },
  { query: 'cheddar cheese', category: 'dairy', requiredAny: ['cheddar'], forbidden: [], expectation: 'resolve' },
  { query: 'mozzarella', category: 'dairy', requiredAny: ['mozzarella'], forbidden: [], expectation: 'resolve' },
  { query: 'parmesan', category: 'dairy', requiredAny: ['parmesan'], forbidden: [], expectation: 'resolve' },
  { query: 'cottage cheese', category: 'dairy', requiredAny: ['cottage'], forbidden: [], expectation: 'resolve' },
  { query: 'cream cheese', category: 'dairy', requiredAny: ['cream', 'cheese'], forbidden: [], expectation: 'resolve' },
  { query: 'butter', category: 'dairy', requiredAny: ['butter'], forbidden: ['peanut'], expectation: 'ambiguous' },
  { query: 'heavy cream', category: 'dairy', requiredAny: ['cream'], forbidden: [], expectation: 'resolve' },
  { query: 'sour cream', category: 'dairy', requiredAny: ['cream'], forbidden: [], expectation: 'resolve' },
  { query: 'feta', category: 'dairy', requiredAny: ['feta'], forbidden: [], expectation: 'resolve' },
  { query: 'swiss cheese', category: 'dairy', requiredAny: ['swiss'], forbidden: [], expectation: 'resolve' },
  { query: 'banana', category: 'produce', requiredAny: ['banana'], forbidden: [], expectation: 'resolve' },
  { query: 'apple', category: 'produce', requiredAny: ['apple'], forbidden: [], expectation: 'ambiguous' },
  { query: 'orange', category: 'produce', requiredAny: ['orange'], forbidden: [], expectation: 'ambiguous' },
  { query: 'strawberries', category: 'produce', requiredAny: ['strawberr'], forbidden: [], expectation: 'resolve' },
  { query: 'blueberries', category: 'produce', requiredAny: ['blueberr'], forbidden: [], expectation: 'resolve' },
  { query: 'grapes', category: 'produce', requiredAny: ['grape'], forbidden: [], expectation: 'resolve' },
  { query: 'avocado', category: 'produce', requiredAny: ['avocado'], forbidden: [], expectation: 'resolve' },
  { query: 'broccoli', category: 'produce', requiredAny: ['broccoli'], forbidden: [], expectation: 'resolve' },
  { query: 'spinach', category: 'produce', requiredAny: ['spinach'], forbidden: [], expectation: 'resolve' },
  { query: 'kale', category: 'produce', requiredAny: ['kale'], forbidden: [], expectation: 'resolve' },
  { query: 'carrot', category: 'produce', requiredAny: ['carrot'], forbidden: [], expectation: 'resolve' },
  { query: 'tomato', category: 'produce', requiredAny: ['tomato'], forbidden: [], expectation: 'ambiguous' },
  { query: 'cucumber', category: 'produce', requiredAny: ['cucumber'], forbidden: [], expectation: 'resolve' },
  { query: 'lettuce', category: 'produce', requiredAny: ['lettuce'], forbidden: [], expectation: 'resolve' },
  { query: 'onion', category: 'produce', requiredAny: ['onion'], forbidden: [], expectation: 'resolve' },
  { query: 'garlic', category: 'produce', requiredAny: ['garlic'], forbidden: [], expectation: 'resolve' },
  { query: 'bell pepper', category: 'produce', requiredAny: ['pepper'], forbidden: [], expectation: 'resolve' },
  { query: 'mushrooms', category: 'produce', requiredAny: ['mushroom'], forbidden: [], expectation: 'resolve' },
  { query: 'green beans', category: 'produce', requiredAny: ['bean'], forbidden: [], expectation: 'resolve' },
  { query: 'peas', category: 'produce', requiredAny: ['pea'], forbidden: [], expectation: 'resolve' },
  { query: 'cauliflower', category: 'produce', requiredAny: ['cauliflower'], forbidden: [], expectation: 'resolve' },
  { query: 'zucchini', category: 'produce', requiredAny: ['zucchini'], forbidden: [], expectation: 'resolve' },
  { query: 'asparagus', category: 'produce', requiredAny: ['asparagus'], forbidden: [], expectation: 'resolve' },
  { query: 'mango', category: 'produce', requiredAny: ['mango'], forbidden: [], expectation: 'resolve' },
  { query: 'pineapple', category: 'produce', requiredAny: ['pineapple'], forbidden: [], expectation: 'resolve' },
  { query: 'watermelon', category: 'produce', requiredAny: ['watermelon'], forbidden: [], expectation: 'resolve' },
  { query: 'peach', category: 'produce', requiredAny: ['peach'], forbidden: [], expectation: 'resolve' },
  { query: 'pear', category: 'produce', requiredAny: ['pear'], forbidden: [], expectation: 'resolve' },
  { query: 'peanut butter', category: 'fats_condiments', requiredAny: ['peanut'], forbidden: [], expectation: 'resolve' },
  { query: 'almond butter', category: 'fats_condiments', requiredAny: ['almond'], forbidden: ['peanut'], expectation: 'resolve' },
  { query: 'almonds', category: 'fats_condiments', requiredAny: ['almond'], forbidden: [], expectation: 'resolve' },
  { query: 'walnuts', category: 'fats_condiments', requiredAny: ['walnut'], forbidden: [], expectation: 'resolve' },
  { query: 'cashews', category: 'fats_condiments', requiredAny: ['cashew'], forbidden: [], expectation: 'resolve' },
  { query: 'olive oil', category: 'fats_condiments', requiredAny: ['olive'], forbidden: [], expectation: 'resolve' },
  { query: 'coconut oil', category: 'fats_condiments', requiredAny: ['coconut'], forbidden: [], expectation: 'resolve' },
  { query: 'mayonnaise', category: 'fats_condiments', requiredAny: ['mayo'], forbidden: [], expectation: 'resolve' },
  { query: 'ketchup', category: 'fats_condiments', requiredAny: ['ketchup'], forbidden: [], expectation: 'resolve' },
  { query: 'mustard', category: 'fats_condiments', requiredAny: ['mustard'], forbidden: [], expectation: 'resolve' },
  { query: 'soy sauce', category: 'fats_condiments', requiredAny: ['soy'], forbidden: [], expectation: 'resolve' },
  { query: 'hot sauce', category: 'fats_condiments', requiredAny: ['sauce'], forbidden: [], expectation: 'ambiguous' },
  { query: 'honey', category: 'fats_condiments', requiredAny: ['honey'], forbidden: [], expectation: 'resolve' },
  { query: 'maple syrup', category: 'fats_condiments', requiredAny: ['maple', 'syrup'], forbidden: [], expectation: 'resolve' },
  { query: 'hummus', category: 'fats_condiments', requiredAny: ['hummus'], forbidden: [], expectation: 'resolve' },
  { query: 'guacamole', category: 'fats_condiments', requiredAny: ['guacamole'], forbidden: [], expectation: 'resolve' },
  { query: 'salsa', category: 'fats_condiments', requiredAny: ['salsa'], forbidden: [], expectation: 'resolve' },
  { query: 'chia seeds', category: 'fats_condiments', requiredAny: ['chia'], forbidden: [], expectation: 'resolve' },
  { query: 'peanuts', category: 'fats_condiments', requiredAny: ['peanut'], forbidden: [], expectation: 'resolve' },
  { query: 'quaker oats', category: 'branded', requiredAny: ['oat', 'quaker'], forbidden: [], expectation: 'resolve' },
  { query: 'cheerios', category: 'branded', requiredAny: ['cheerio'], forbidden: [], expectation: 'resolve' },
  { query: 'coca cola', category: 'branded', requiredAny: ['cola'], forbidden: [], expectation: 'resolve' },
  { query: 'pepsi', category: 'branded', requiredAny: ['pepsi'], forbidden: [], expectation: 'resolve' },
  { query: 'oreo', category: 'branded', requiredAny: ['oreo'], forbidden: [], expectation: 'resolve' },
  { query: 'nutella', category: 'branded', requiredAny: ['nutella'], forbidden: [], expectation: 'resolve' },
  { query: 'kind bar', category: 'branded', requiredAny: ['kind'], forbidden: [], expectation: 'ambiguous' },
  { query: 'clif bar', category: 'branded', requiredAny: ['clif'], forbidden: [], expectation: 'resolve' },
  { query: 'gatorade', category: 'branded', requiredAny: ['gatorade'], forbidden: [], expectation: 'resolve' },
  { query: 'doritos', category: 'branded', requiredAny: ['dorito'], forbidden: [], expectation: 'resolve' },
  { query: 'pringles', category: 'branded', requiredAny: ['pringle'], forbidden: [], expectation: 'resolve' },
  { query: 'ben and jerrys', category: 'branded', requiredAny: ['jerry'], forbidden: [], expectation: 'ambiguous' },
  { query: 'chobani', category: 'branded', requiredAny: ['chobani'], forbidden: [], expectation: 'resolve' },
  { query: 'kelloggs corn flakes', category: 'branded', requiredAny: ['flake', 'corn'], forbidden: [], expectation: 'resolve' },
  { query: 'heinz ketchup', category: 'branded', requiredAny: ['ketchup', 'heinz'], forbidden: [], expectation: 'resolve' },
  { query: 'campbells soup', category: 'branded', requiredAny: ['soup', 'campbell'], forbidden: [], expectation: 'resolve' },
  { query: 'lays chips', category: 'branded', requiredAny: ['chip', 'lay'], forbidden: [], expectation: 'ambiguous' },
  { query: 'starbucks coffee', category: 'branded', requiredAny: ['coffee', 'starbuck'], forbidden: [], expectation: 'resolve' },
  { query: 'chiken breast', category: 'misspelling', requiredAny: ['chicken'], forbidden: ['turkey', 'pork', 'beef'], expectation: 'resolve' },
  { query: 'brocoli', category: 'misspelling', requiredAny: ['broccoli'], forbidden: [], expectation: 'resolve' },
  { query: 'bannana', category: 'misspelling', requiredAny: ['banana'], forbidden: [], expectation: 'resolve' },
  { query: 'yoghurt', category: 'misspelling', requiredAny: ['yog'], forbidden: [], expectation: 'resolve' },
  { query: 'avacado', category: 'misspelling', requiredAny: ['avocado'], forbidden: [], expectation: 'resolve' },
  { query: 'brocolli', category: 'misspelling', requiredAny: ['broccoli'], forbidden: [], expectation: 'resolve' },
  { query: 'tomatoe', category: 'misspelling', requiredAny: ['tomato'], forbidden: [], expectation: 'resolve' },
  { query: 'spinnach', category: 'misspelling', requiredAny: ['spinach'], forbidden: [], expectation: 'resolve' },
  { query: 'chedar cheese', category: 'misspelling', requiredAny: ['cheddar'], forbidden: [], expectation: 'resolve' },
  { query: 'peanutbutter', category: 'misspelling', requiredAny: ['peanut'], forbidden: [], expectation: 'resolve' },
  { query: 'salmoon', category: 'misspelling', requiredAny: ['salmon'], forbidden: ['tuna'], expectation: 'resolve' },
  { query: 'potatoe', category: 'misspelling', requiredAny: ['potato'], forbidden: [], expectation: 'resolve' },
  { query: 'cucumbr', category: 'misspelling', requiredAny: ['cucumber'], forbidden: [], expectation: 'resolve' },
  { query: 'strawbery', category: 'misspelling', requiredAny: ['strawberr'], forbidden: [], expectation: 'resolve' },
  { query: 'mozarella', category: 'misspelling', requiredAny: ['mozzarella'], forbidden: [], expectation: 'resolve' },
  { query: 'cauliflour', category: 'misspelling', requiredAny: ['cauliflower'], forbidden: [], expectation: 'resolve' },
  { query: 'asparagas', category: 'misspelling', requiredAny: ['asparagus'], forbidden: [], expectation: 'resolve' },
  { query: 'quinao', category: 'misspelling', requiredAny: ['quinoa'], forbidden: [], expectation: 'resolve' },
  { query: 'bluberries', category: 'misspelling', requiredAny: ['blueberr'], forbidden: [], expectation: 'resolve' },
  { query: 'sandwhich', category: 'misspelling', requiredAny: ['sandwich'], forbidden: [], expectation: 'ambiguous' },
  { query: 'brocolli rabe', category: 'misspelling', requiredAny: ['broccoli'], forbidden: [], expectation: 'resolve' },
  { query: 'chikpeas', category: 'misspelling', requiredAny: ['chickpea'], forbidden: [], expectation: 'resolve' },
  { query: 'lentels', category: 'misspelling', requiredAny: ['lentil'], forbidden: [], expectation: 'resolve' },
  { query: 'pinapple', category: 'misspelling', requiredAny: ['pineapple'], forbidden: [], expectation: 'resolve' },
  { query: 'zuchini', category: 'misspelling', requiredAny: ['zucchini'], forbidden: [], expectation: 'resolve' },
  { query: 'pb', category: 'abbreviation', requiredAny: ['peanut'], forbidden: [], expectation: 'resolve' },
  { query: 'pb and j', category: 'abbreviation', requiredAny: ['peanut'], forbidden: [], expectation: 'resolve' },
  { query: 'og chicken', category: 'abbreviation', requiredAny: ['chicken'], forbidden: ['turkey'], expectation: 'resolve' },
  { query: 'bbq sauce', category: 'abbreviation', requiredAny: ['barbecue', 'sauce'], forbidden: [], expectation: 'resolve' },
  { query: 'choc milk', category: 'abbreviation', requiredAny: ['chocolate', 'milk'], forbidden: [], expectation: 'resolve' },
  { query: 'ww bread', category: 'abbreviation', requiredAny: ['wheat', 'bread'], forbidden: [], expectation: 'resolve' },
  { query: 'veg soup', category: 'abbreviation', requiredAny: ['vegetable', 'soup'], forbidden: [], expectation: 'resolve' },
  { query: 'gf bread', category: 'abbreviation', requiredAny: ['gluten', 'bread'], forbidden: [], expectation: 'resolve' },
  { query: 'evoo', category: 'abbreviation', requiredAny: ['olive'], forbidden: [], expectation: 'resolve' },
  { query: 'choc chip cookie', category: 'abbreviation', requiredAny: ['chocolate', 'cookie'], forbidden: [], expectation: 'resolve' },
  { query: 'veg stir fry', category: 'abbreviation', requiredAny: ['vegetable'], forbidden: [], expectation: 'ambiguous' },
  { query: 'bananas', category: 'morphology', requiredAny: ['banana'], forbidden: [], expectation: 'resolve' },
  { query: 'apples', category: 'morphology', requiredAny: ['apple'], forbidden: [], expectation: 'ambiguous' },
  { query: 'carrots', category: 'morphology', requiredAny: ['carrot'], forbidden: [], expectation: 'resolve' },
  { query: 'tomatoes', category: 'morphology', requiredAny: ['tomato'], forbidden: [], expectation: 'ambiguous' },
  { query: 'potatoes', category: 'morphology', requiredAny: ['potato'], forbidden: [], expectation: 'ambiguous' },
  { query: 'almond', category: 'morphology', requiredAny: ['almond'], forbidden: [], expectation: 'resolve' },
  { query: 'egg', category: 'morphology', requiredAny: ['egg'], forbidden: [], expectation: 'resolve' },
  { query: 'berries', category: 'morphology', requiredAny: ['berr'], forbidden: [], expectation: 'ambiguous' },
  { query: 'cherries', category: 'morphology', requiredAny: ['cherr'], forbidden: [], expectation: 'resolve' },
  { query: 'sandwiches', category: 'morphology', requiredAny: ['sandwich'], forbidden: [], expectation: 'ambiguous' },
  { query: 'a cup of white rice', category: 'natural_language', requiredAny: ['rice'], forbidden: [], expectation: 'resolve' },
  { query: 'two scrambled eggs', category: 'natural_language', requiredAny: ['egg'], forbidden: [], expectation: 'resolve' },
  { query: 'some grilled chicken', category: 'natural_language', requiredAny: ['chicken'], forbidden: ['turkey'], expectation: 'resolve' },
  { query: 'i had a banana', category: 'natural_language', requiredAny: ['banana'], forbidden: [], expectation: 'resolve' },
  { query: 'half an avocado', category: 'natural_language', requiredAny: ['avocado'], forbidden: [], expectation: 'resolve' },
  { query: 'a slice of whole wheat bread', category: 'natural_language', requiredAny: ['bread'], forbidden: [], expectation: 'resolve' },
  { query: 'bowl of oatmeal', category: 'natural_language', requiredAny: ['oat'], forbidden: [], expectation: 'resolve' },
  { query: 'glass of whole milk', category: 'natural_language', requiredAny: ['milk'], forbidden: [], expectation: 'resolve' },
  { query: 'add greek yogurt', category: 'natural_language', requiredAny: ['yogurt'], forbidden: [], expectation: 'resolve' },
  { query: 'log two eggs', category: 'natural_language', requiredAny: ['egg'], forbidden: [], expectation: 'resolve' },
  { query: '100 grams of chicken', category: 'natural_language', requiredAny: ['chicken'], forbidden: ['turkey'], expectation: 'ambiguous' },
  { query: 'a piece of salmon', category: 'natural_language', requiredAny: ['salmon'], forbidden: ['tuna'], expectation: 'resolve' },
  { query: 'raw broccoli', category: 'preparation', requiredAny: ['broccoli'], forbidden: [], expectation: 'resolve' },
  { query: 'steamed broccoli', category: 'preparation', requiredAny: ['broccoli'], forbidden: [], expectation: 'resolve' },
  { query: 'boiled potato', category: 'preparation', requiredAny: ['potato'], forbidden: [], expectation: 'resolve' },
  { query: 'fried egg', category: 'preparation', requiredAny: ['egg'], forbidden: [], expectation: 'resolve' },
  { query: 'roasted vegetables', category: 'preparation', requiredAny: ['vegetable'], forbidden: [], expectation: 'ambiguous' },
  { query: 'baked salmon', category: 'preparation', requiredAny: ['salmon'], forbidden: ['tuna'], expectation: 'resolve' },
  { query: 'raw spinach', category: 'preparation', requiredAny: ['spinach'], forbidden: [], expectation: 'resolve' },
  { query: 'cooked quinoa', category: 'preparation', requiredAny: ['quinoa'], forbidden: [], expectation: 'resolve' },
  { query: 'dried apricots', category: 'preparation', requiredAny: ['apricot'], forbidden: [], expectation: 'resolve' },
  { query: 'frozen berries', category: 'preparation', requiredAny: ['berr'], forbidden: [], expectation: 'ambiguous' },
  { query: 'canned beans', category: 'preparation', requiredAny: ['bean'], forbidden: [], expectation: 'ambiguous' },
  { query: 'smoked salmon', category: 'preparation', requiredAny: ['salmon'], forbidden: ['tuna'], expectation: 'resolve' },
  { query: 'sushi', category: 'cuisine', requiredAny: ['sushi'], forbidden: [], expectation: 'ambiguous' },
  { query: 'pad thai', category: 'cuisine', requiredAny: ['thai', 'pad'], forbidden: [], expectation: 'resolve' },
  { query: 'burrito', category: 'cuisine', requiredAny: ['burrito'], forbidden: [], expectation: 'ambiguous' },
  { query: 'taco', category: 'cuisine', requiredAny: ['taco'], forbidden: [], expectation: 'ambiguous' },
  { query: 'pizza', category: 'cuisine', requiredAny: ['pizza'], forbidden: [], expectation: 'ambiguous' },
  { query: 'lasagna', category: 'cuisine', requiredAny: ['lasagna'], forbidden: [], expectation: 'resolve' },
  { query: 'falafel', category: 'cuisine', requiredAny: ['falafel'], forbidden: [], expectation: 'resolve' },
  { query: 'naan', category: 'cuisine', requiredAny: ['naan'], forbidden: [], expectation: 'resolve' },
  { query: 'kimchi', category: 'cuisine', requiredAny: ['kimchi'], forbidden: [], expectation: 'resolve' },
  { query: 'miso soup', category: 'cuisine', requiredAny: ['miso'], forbidden: [], expectation: 'resolve' },
  { query: 'ramen', category: 'cuisine', requiredAny: ['ramen'], forbidden: [], expectation: 'ambiguous' },
  { query: 'curry', category: 'cuisine', requiredAny: ['curry'], forbidden: [], expectation: 'ambiguous' },
  { query: 'paella', category: 'cuisine', requiredAny: ['paella'], forbidden: [], expectation: 'resolve' },
  { query: 'gyro', category: 'cuisine', requiredAny: ['gyro'], forbidden: [], expectation: 'resolve' },
  { query: 'pho', category: 'cuisine', requiredAny: ['pho'], forbidden: [], expectation: 'resolve' },
  { query: 'empanada', category: 'cuisine', requiredAny: ['empanada'], forbidden: [], expectation: 'resolve' },
  { query: 'dumplings', category: 'cuisine', requiredAny: ['dumpling'], forbidden: [], expectation: 'resolve' },
  { query: 'couscous salad', category: 'cuisine', requiredAny: ['couscous'], forbidden: [], expectation: 'resolve' },
  { query: 'chicken', category: 'ambiguous', requiredAny: ['chicken'], forbidden: ['turkey'], expectation: 'ambiguous' },
  { query: 'cheese', category: 'ambiguous', requiredAny: ['cheese'], forbidden: [], expectation: 'ambiguous' },
  { query: 'bar', category: 'ambiguous', requiredAny: ['bar'], forbidden: [], expectation: 'ambiguous' },
  { query: 'juice', category: 'ambiguous', requiredAny: ['juice'], forbidden: [], expectation: 'ambiguous' },
  { query: 'soup', category: 'ambiguous', requiredAny: ['soup'], forbidden: [], expectation: 'ambiguous' },
  { query: 'salad', category: 'ambiguous', requiredAny: ['salad'], forbidden: [], expectation: 'ambiguous' },
  { query: 'smoothie', category: 'ambiguous', requiredAny: ['smoothie'], forbidden: [], expectation: 'ambiguous' },
  { query: 'shake', category: 'ambiguous', requiredAny: ['shake'], forbidden: [], expectation: 'ambiguous' },
  { query: 'wrap', category: 'ambiguous', requiredAny: ['wrap'], forbidden: [], expectation: 'ambiguous' },
  { query: 'sandwich', category: 'ambiguous', requiredAny: ['sandwich'], forbidden: [], expectation: 'ambiguous' },
  { query: 'water', category: 'ambiguous', requiredAny: ['water'], forbidden: [], expectation: 'ambiguous' },
  { query: 'coffee', category: 'ambiguous', requiredAny: ['coffee'], forbidden: [], expectation: 'ambiguous' },
  { query: 'tea', category: 'ambiguous', requiredAny: ['tea'], forbidden: [], expectation: 'ambiguous' },
  { query: 'beans', category: 'ambiguous', requiredAny: ['bean'], forbidden: [], expectation: 'ambiguous' },
  { query: 'nuts', category: 'ambiguous', requiredAny: ['nut'], forbidden: [], expectation: 'ambiguous' },
  { query: 'crackers', category: 'ambiguous', requiredAny: ['cracker'], forbidden: [], expectation: 'ambiguous' },
  { query: 'xyzzy', category: 'absent', requiredAny: [], forbidden: [], expectation: 'absent' },
  { query: 'qwertyfood', category: 'absent', requiredAny: [], forbidden: [], expectation: 'absent' },
  { query: 'asdfghjkl', category: 'absent', requiredAny: [], forbidden: [], expectation: 'absent' },
  { query: 'zzzzzzzz', category: 'absent', requiredAny: [], forbidden: [], expectation: 'absent' },
  { query: 'flurbleberry', category: 'absent', requiredAny: [], forbidden: [], expectation: 'absent' },
  { query: 'nonexistentfood', category: 'absent', requiredAny: [], forbidden: [], expectation: 'absent' },
  { query: 'blorptato', category: 'absent', requiredAny: [], forbidden: [], expectation: 'absent' },
  { query: 'grumbleflax', category: 'absent', requiredAny: [], forbidden: [], expectation: 'absent' },
];
